services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lifetrackhub
      - MYSQL_USER=lifetrackhub
      - MYSQL_PASSWORD=lifetrackhub